[package]
name = "htmx-starter"
version = "0.1.0"
edition = "2021"

[workspace]
members = [ "./src/templates/htmx-rust" , "src/templates/htmx-rust"]

[dependencies]
clap = "4.5.8"
indicatif = "0.17.8"
inquire = "0.7.5"
fs_extra = "1.3.0"
serde = { version = "1.0", features = ["derive"] }
